name: Check for errors

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: DeLaGuardo/clojure-lint-action@master
      with:
        clj-kondo-args: --lint src
        check-name: Linting with clj-kondo
        github_token: ${{ secrets.GITHUB_TOKEN }}
