on:
  push
  pull_request:
    types: [synchronize, opened, edited]

name: Push / PR Builder

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: DeLaGuardo/setup-clj-kondo@v1

    - uses: actions/checkout@v2

    - name: Lint
      run: clj-kondo --lint src --config '{:output {:pattern "::{{level}} file={{filename}},line={{row}},col={{col}}::{{message}}"}}'
