on:
  push:
    branches:
      - master
  pull_request:
    types: [synchronize, opened, edited]

name: Push / PR Builder

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: DeLaGuardo/setup-clj-kondo@master
      with:
        version: '2021.07.28'

    - uses: actions/checkout@v2

    - name: Lint
      run: clj-kondo --lint src --config resources/clj-kondo.exports/net.clojars.heyitscassio/teleconj/config.edn --config '{:output {:pattern "::{{level}} file={{filename}},line={{row}},col={{col}}::{{message}}"}}'
