on:
  push:
    branches:
      - master
  pull_request:
    types: [synchronize, opened, edited]

name: Linting

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2023.10.20'

      - name: Run clj-kondo
        run: |
          clj-kondo --lint src --config '{:output {:pattern "::{{level}} file={{filename}},line={{row}},col={{col}}::{{message}}"}}'
